namespace AutoGeneratedDomainModels
{
	
	public class Prescription
	{
		public Prescription()
		{
		}
		public int Dosage	{ get; set; }
		public string Drug	{ get; set; }
		public string Patient	{ get; set; }
		public System.DateTime Date	{ get; set; }
	}
}
